apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: hound
spec:
  acme:
    config:
    - domains:
      - {{ .Values.domain }}
      http01:
        ingress: ""
  commonName: ""
  dnsNames:
  - {{ .Values.domain }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: hound-certs