kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: hound
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-signin: https://{{ .Values.domain }}/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: https://{{ .Values.domain }}/oauth2/auth
  labels:
    app: hound
    chart: hound-chart
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  rules:
  - host: {{ .Values.domain }}
    http: 
      paths:
      - path: /
        backend:
          serviceName: hound
          servicePort: 6080
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: hound-certs
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: hound-oauth2-proxy
  labels:
    app: hound
    chart: hound-chart
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  rules:
  - host: {{ .Values.domain }}
    http: 
      paths:
      - path: /oauth2
        backend:
          serviceName: hound-oauth2-proxy
          servicePort: 4180