apiVersion: v1
kind: Secret
metadata:
  name: hound
  labels:
    app: hound
    chart: hound-chart
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  config: |-
    {
        "max-concurrent-indexers" : 2,
        "dbpath" : "/home/db",
        "health-check-uri" : "/healthz",
        "repos" : {
          {{- range $key, $value := .Values.repositories }}
            "{{ $key | title }}Repo" : {
                "url" : "https://{{ $value.username }}:{{ $value.token }}@github.com/{{ $value.owner }}/{{ $key }}",
                "ms-between-poll": 300000,
                "exclude-dot-files": true
            }
          {{- end }}
        }
    }